services:
  php:
    build: .
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: rootpass 
    volumes:
      - db_data:/var/lib/mysql
      - ./db/employees.sql:/docker-entrypoint-initdb.d/employees.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - db

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"

volumes:
  db_data:
  portainer_data:
